### ISSUE TITLE
PA Review: New Account creation, login, demo login

### ISSUE THREAD

**Issue by Jacwutang** [Jacwutang/OpenTummy#3]
- [x] Backend - New Account creation

- [x] Backend - Sign In

- [x] Backend - logout

- [x] Backend - demo login

- [x] Frontend styling

https://opentummy.herokuapp.com/

**Comment by evhumphrey** [comment]
Go ahead and set up heroku so I can see what it looks like 👍

**Comment by Jacwutang** [comment]
uhhh my db isn't being recognized by heroku....

**Comment by evhumphrey** [comment]
Still having heroku issues?

**Comment by evhumphrey** [comment]
Nice job on user auth!

I'm gonna require some more styling though. While the basic structure and layout is there, currently, it's a bit crowded, lacks a consistent color theme (purple, grey, red, blue), and meaningful text is not sized appropriately. 

To put those words into a picture:

![user_auth_feedback](https://user-images.githubusercontent.com/6361824/33189685-14508b38-d05a-11e7-9e29-9c6b12eeadfc.png)

Let me know if you have any questions about this feedback!

**Comment by Jacwutang** [comment]
Working on adding more styling and keeping it consistent

**Comment by Jacwutang** [comment]
FrontEnd Auth MVP ready for review

**Comment by evhumphrey** [comment]
- [ ] Consistent font - use sans-serif fonts
- [ ] Increase size of text on session forms

**Comment by evhumphrey** [comment]
- [ ] add `button:hover { cursor: pointer};` to your css 
- [ ] add some sort of background-color change on `button:hover` (`#de5656` might be a good color choice)
should be good after that!

**Comment by Jacwutang** [comment]
Should be good to go

**Comment by evhumphrey** [comment]
Nice! Gonna close this, but at some point you should make your minimum password length > 1
